name: Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/simple-api-go:latest

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.actor }}/simple-api-go:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MAIN_SSH_HOST }}
        username: ${{ secrets.MAIN_SSH_USERNAME }}
        key: ${{ secrets.MAIN_SSH_KEY }}
        script: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_PAT }}
          docker pull ghcr.io/${{ github.actor }}/simple-api-go:latest
          cd api
          docker-compose up -d