name: CICD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login github
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{secrets.GHCR_PAT}}
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag 
